### ISSUE TITLE
Web Console

### ISSUE THREAD

**Issue by ForgivenNin** [cyruscook/LoadingScreen#2]
Hello again,
I'm thankful for your help on the last problem; I just have been left with one more question that you would better know the answer to than I do.

I typed in my code into the web console, and it did work! However, it won't go away. Is it that I'm trying to use it in a way that the timer function can't work with?

_Unfortunately I would have posted this issue on my own fork, but it's not possible :P_

**Comment by cyruscook** [comment]
Can you ellaborate on the purpose of your code, like what do you want it to do? It's just because I don't understand why it would be pasted into a console, the idea of this project is to have it in the code of your website to display while your website loads.

If you add it into the console of a page, then your going to be putting a loading screen on a page that is already loaded, and I really don't understand the purpose of that.

So could you elaborate a bit on what exactly you want your code to do, so that I can help you?

**Comment by ForgivenNin** [comment]
My goal is for it to be able to run in the background - whenever you load up a page, the loading screen appears. At first, my thought was it has to be ran in the console; but a  second thought may be of just having a file to execute.

**Comment by cyruscook** [comment]
So you want it as a browser extension which places the loading screen on any website that a client visits?

Or do you want it as code on a specific website so that any client that visits that website will see the loading screen?

For the former Im not sure who's going to paste some code into the console on every website that they visit, that would have to be a browser extension, and even then I would not recommend this as it might interfere with some websites.

Is it the latter? If so why are you running it in the console? You should place it at the top of the HTML file.

**Comment by ForgivenNin** [comment]
You could say that yeah. But as far as I know for it to become and extension there would have to be a dependency, and I've never used a framework, package, or extension before.

Other than that the only solution I can see is turning it into a loop and the user would then have to run the file.

This would be for loading any webpage on the internet, not from hosting a website.

**Comment by cyruscook** [comment]
This would definately involve creating a chrome extension and making the script be injected before the page is loaded, however I dont know how to do that or even if its possible.

I'm closing this issue as I don't believe it is related specifically to my loading screen anymore, I recommend you search up how to make chrome extensions.
